/**
 * Reconcile graph model elements into Vue Flow elements by id.
 *
 * Keeping unchanged flow objects is intentional: Vue Flow stores transient
 * render state (selection, dimensions and visibility) on those objects.  A
 * complete replacement discards that state even when only one node changed.
 */
export interface Identified {
  id: string
}

export interface PatchResult<T extends Identified> {
  items: T[]
  added: number
  updated: number
  removed: number
}

/**
 * Builds the next render list in model order while preserving fields which
 * belong only to the renderer.  The projector remains the sole authority for
 * document-backed fields, so a model change always wins over stale canvas data.
 */
export function patchById<Source extends Identified, Flow extends Identified>(
  current: readonly Flow[],
  source: readonly Source[],
  project: (source: Source) => Flow,
): PatchResult<Flow> {
  const existing = new Map(current.map((item) => [item.id, item]))
  const sourceIds = new Set(source.map((item) => item.id))
  let added = 0
  let updated = 0

  const items = source.map((item) => {
    const next = project(item)
    const previous = existing.get(item.id)
    if (!previous) {
      added += 1
      return next
    }
    updated += 1
    // Spread previous first so renderer-only keys such as selected/dimensions
    // survive, then replace document-backed keys generated by the projector.
    return { ...previous, ...next }
  })

  return {
    items,
    added,
    updated,
    removed: current.reduce((count, item) => count + (sourceIds.has(item.id) ? 0 : 1), 0),
  }
}
