/**
 * Reconcile graph model elements into Vue Flow elements by id.
 *
 * Keeping unchanged flow objects is intentional: Vue Flow stores transient
 * render state (selection, dimensions and visibility) on those objects.  A
 * complete replacement discards that state even when only one node changed.
 */
export interface Identified {
  id: string
}

export interface PatchResult<T extends Identified> {
  items: T[]
  added: number
  updated: number
  removed: number
}

/**
 * Builds the next render list in model order while preserving fields which
 * belong only to the renderer.  The projector remains the sole authority for
 * document-backed fields, so a model change always wins over stale canvas data.
 */
export function patchById<Source extends Identified, Flow extends Identified>(
  current: readonly Flow[],
  source: readonly Source[],
  project: (source: Source) => Flow,
): PatchResult<Flow> {
  const existing = new Map(current.map((item) => [item.id, item]))
  const sourceIds = new Set(source.map((item) => item.id))
  let added = 0
  let updated = 0

  const items = source.map((item) => {
    const next = project(item)
    const previous = existing.get(item.id)
    if (!previous) {
      added += 1
      return next
    }
    updated += 1
    // Spread previous first so renderer-only keys such as selected/dimensions
    // survive, then replace document-backed keys generated by the projector.
    return { ...previous, ...next }
  })

  return {
    items,
    added,
    updated,
    removed: current.reduce((count, item) => count + (sourceIds.has(item.id) ? 0 : 1), 0),
  }
}

/* ---------- Task 18（§5.1）边流动动画 ---------- */

/** 流动边判定的运行态集合：两端节点皆 executing/executed（plan Task 18 口径） */
const EDGE_FLOW_STATES = new Set(['executing', 'executed'])

/** 追加到边 class 上的流动动画类（theme.css 定义 stroke-dashoffset 关键帧） */
export const EDGE_FLOWING_CLASS = 'edge-flowing'

/**
 * 计算处于「流动」状态的边 id 集合：数据流向 source→target，两端节点状态
 * 均在 EDGE_FLOW_STATES 内才流动（纯函数，GraphWorkbench 据此增删 flow edge class）。
 */
export function flowingEdgeIds(
  edges: readonly { id: string; source: string; target: string }[],
  nodeStates: Record<string, { state?: string } | undefined> | Record<string, string>,
): Set<string> {
  const flowing = new Set<string>()
  for (const e of edges) {
    const s = nodeStates[e.source]
    const t = nodeStates[e.target]
    const ss = typeof s === 'string' ? s : s?.state
    const ts = typeof t === 'string' ? t : t?.state
    if (ss && ts && EDGE_FLOW_STATES.has(ss) && EDGE_FLOW_STATES.has(ts)) flowing.add(e.id)
  }
  return flowing
}
